#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# start compositor
# picom --config ~/.config/bspwm/picom.conf &

bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a firefox desktop='^2' state=floating
bspc rule -a obsidian desktop='^3' follow=on state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config focus_follows_pointer true

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

xrdb merge ~/.Xresources

~/.config/polybar/launch.sh
~/.config/polybar/init_bar.sh &
~/.config/bspwm/scripts/wallpaper.sh &

# rules
bspc rule -a feh state=floating
# bspc rule -a firefox state=floating

(sleep 1 && ~/.config/polybar/init_bar.sh) &

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

